language: python
env:
  global:
    - NOSE_NOLOGCAPTURE=true
    - NOSE_VERBOSE=2
    - NOSE_WITH_COVERAGE=true
    - NOSE_COVER_PACKAGE=neovim
python:
  # If the build matrix gets bigger, also update the number of runs
  # at the bottom of .scrutinizer.yml.
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install expect -q
  - git clone --depth=1 -b master git://github.com/neovim/neovim nvim
  - sudo git clone --depth=1 git://github.com/neovim/deps /opt/neovim-deps
  - pip install -q flake8 flake8-import-order flake8-docstrings pep8-naming
  - pip install -q scrutinizer-ocular
install:
  - pip install .
  - prefix="/opt/neovim-deps/64"
  - eval $($prefix/usr/bin/luarocks path)
  - export PATH="$prefix/usr/bin:$PATH"
  - export PKG_CONFIG_PATH="$prefix/usr/lib/pkgconfig"
  - export USE_BUNDLED_DEPS=OFF
  - cd nvim && make && cd ..
before_script:
  - flake8 --exclude ./neovim/plugins neovim
script:
  - ./nvim/scripts/run-api-tests.exp "nosetests" "./nvim/build/bin/nvim -u NONE"
  - NVIM_SPAWN_ARGV='["./nvim/build/bin/nvim", "-u", "NONE", "--embed"]' nosetests
after_success:
  - ocular
